version: '3'

networks:
  postgres:
    driver: bridge

services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: 'UTC'
      PGTZ: 'UTC'
    volumes:
      - ./postgres_database:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres

  postgres_bkp:
    image: postgres_bkp
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  postgres: